numberForPassExam: 3
spring:
  messages:
    basename: i18n/messages
    fallback-to-system:
      locale: false
logging:
  level:
    org:
      springframework:
        web: ERROR
    com:
      samsung: DEBUG