spring:
  messages:
    basename: i18n/messages
  shell:
    interactive:
      enabled: false
numberForPassExam: 3
logging:
  level:
    org:
      springframework:
        web: ERROR
    com:
      samsung: DEBUG